### ISSUE TITLE
add back "update" dashboard

### ISSUE THREAD

**Issue by botheis** [pulse-project/pulse2#188]
<a href="https://github.com/neoclust"><img src="https://avatars1.githubusercontent.com/u/285923?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [neoclust](https://github.com/neoclust)**
_Wednesday Jan 11, 2017 at 10:16 GMT_
_Originally opened as https://github.com/pulse-project/pulse/issues/79_

----

Make sure the "update" dashboard is alive and kickiing

**Comment by botheis** [comment]
<a href="https://github.com/tekmans"><img src="https://avatars1.githubusercontent.com/u/1766087?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tekmans](https://github.com/tekmans)**
_Wednesday Jan 11, 2017 at 10:18 GMT_

----

![selection_117](https://cloud.githubusercontent.com/assets/1766087/21844627/b34fed1e-d7ef-11e6-9a08-e8d334bbe550.png)
![image](https://cloud.githubusercontent.com/assets/1766087/21852762/a334d1fe-d814-11e6-8764-1660c8fb3224.png)

**Comment by botheis** [comment]
<a href="https://github.com/tekmans"><img src="https://avatars1.githubusercontent.com/u/1766087?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tekmans](https://github.com/tekmans)**
_Monday Jan 23, 2017 at 14:30 GMT_

----

Depend on the activation of the plugin /etc/mmc/plugins/update.ini
It needs to be disctinct of windows update module

**Comment by neoclust** [comment]
in progress in mmc-core in "update" branche
