### ISSUE TITLE
Weblate links to source strings

### ISSUE THREAD

**Issue by comradekingu** [pulse-project/pulse2#228]
https://hosted.weblate.org/translate/pulse/ppolicy/nb/?checksum=7f4152548c335e03 does not link to pulse2

![bilde](https://user-images.githubusercontent.com/13802408/37859791-e2036b9a-2f19-11e8-8d8e-7c65a0b52e2b.png)

Where it says "repository browser" http://docs.weblate.org/en/latest/_images/add-component.png

http://docs.weblate.org/en/latest/admin/projects.html#component-configuration

**Comment by spointu** [comment]
I use Weblate all the time to translate pulse project and my translations seem to get integrated in the project, but I don’t know by what means. I’ll discuss this with @neoclust this week.

**Comment by neoclust** [comment]
hello.

I don't recall recall receiving emails.

I will take a look.

**Comment by neoclust** [comment]
this issue is now fixed.

Thanks.
